services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8888:8081"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    env_file:
      - ./.env
    command: npm run dev

  bot:
    build: ./bot
    ports:
      - "3008:3008"
    depends_on:
      - mongo
    volumes:
      - ./bot:/usr/src/bot
      - /usr/src/bot/node_modules
    env_file:
      - ./.env
    command: npm run dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_client:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend

volumes:
  mongo-data: